# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Introduction to Statistics and Data Science
author: Jill O'Reilly & Lindsay Richards
logo: dice.jpg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

mathjax_path: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-MML-AM_CHTML
mathjax2_config: {
    'tex2jax': {
    'inlineMath': [['$', '$'], ['\\(', '\\)']],
    'processEscapes': True,
    'ignoreClass': 'document',
    'processClass': 'math|output_area',
    }
}

# Information about where the book exists on the web
repository:
  url: https://github.com/jillxoreilly/StatsCourseBook  # Online location of your book

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  use_multitoc_numbering: false

# Add Colab buttons to your book
launch_buttons:
  colab_url: "https://colab.research.google.com"

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - html_image
    - amsmath
    - dollarmath
    - html_video

